### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by cryptotiger**
Hi all,
[HowToMakeEvoMasterCompileOnMac.pdf](https://github.com/EMResearch/EvoMaster/files/12438191/HowToMakeEvoMasterCompileOnMac.pdf)

Evomaster could not be built on my MacBook Pro. I have shared a report explaining all my steps to run Evomaster in this pull request. Based on that, I suggest using the version 1.57.2. 

Thanks

### CODE REVIEW

**Comment by arcuri82** [comment]
@cryptotiger  thx Onur ;)

there is currently a problem with CI, that we need to fix before can test this PR

**Comment by arcuri82** [comment]
@man-zhang hi, have you seen such type of issue before? it is related to RPC on Mac. i have now added a build on Mac as well, to verify this kind of issues

**Comment by man-zhang** [comment]
@arcuri82 I will have a look today.

**Comment by man-zhang** [comment]
@arcuri82 hi, I just checked on my Mac and did not meet the problem. But the problem might relate to Apple M1.

**Comment by man-zhang** [comment]
hi, @arcuri82 I asked Seran to build `master` on his Mac (M1 as well). it seems fine, and cannot re-produce this issue.
@cryptotiger can you try to build it again? eg, using the latest `master`

**Comment by cryptotiger** [comment]
Hi all,

I tried to clone Evomaster again to my machine and I got the same problem again. Here is the screenshot:
Screenshot 2023-09-07 at 2 16 06 PM

**Comment by man-zhang** [comment]
@arcuri82 after discussing with Onur, it is somehow related to JDK version, JDK 8 works, but not JDK 11.

**Comment by arcuri82** [comment]
@man-zhang ok. but i guess the increase of version here solves the issue?

**Comment by man-zhang** [comment]
@arcuri82  yes. I checked the version 1.57.2, and it works on my Mac as well.

**Review by arcuri82 — APPROVED** [review]

**Pull request merged**
